version: '3'

services:
  frontend:
    image: frontend
    ports:
      - 9000:9000

  backend:
    image: backend
    environment:
      - DATABASE_HOST: db
    container_name: flask
    ports:
      - 8000:8000

  mysql:
    image: mysql:latest
    MYSQL_ROOT_PASSWORD: ''
    MYSQL_DATABASE: babysearch
    ports:
      - 3306:3306